//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int Id { get; set; }
        public Nullable<int> OldEmployeeId { get; set; }
        public Nullable<int> NewEmployeeId { get; set; }
        public Nullable<System.DateTime> OldReportDate { get; set; }
        public Nullable<System.DateTime> NewReportDate { get; set; }
        public string OldTask { get; set; }
        public string NewTask { get; set; }
        public Nullable<double> OldExecutionHours { get; set; }
        public Nullable<double> NewExecutionHours { get; set; }
        public string OldComments { get; set; }
        public string NewComments { get; set; }
        public string Command { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
