//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BgTatkoForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Threads = new HashSet<Thread>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Desription { get; set; }
    
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
