//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BgTatkoForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Posts = new HashSet<Post>();
            this.ThreadVotes = new HashSet<ThreadVote>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int ThreadId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserId { get; set; }
        public int Vote { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ThreadVote> ThreadVotes { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
