//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BgTatkoForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Posts = new HashSet<Post>();
            this.PostVotes = new HashSet<PostVote>();
            this.Threads = new HashSet<Thread>();
            this.ThreadVotes = new HashSet<ThreadVote>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PostVote> PostVotes { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
        public virtual ICollection<ThreadVote> ThreadVotes { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
